unit uConstantesTeste;

interface

const
  CODIGO_BUSCAR_POR_CODIGO = 1; //Semente de milho
  CODIGO_PRODUTO_INCORRETO = 'Código do produto incorreto';
  CODIGO_PRODUTO_NAO_ENCONTRADO = 99999;

  DESCRICAO_TESTE_PADRAO = 'SOJA';
  DESCRICAO_PRODUTO_INEXISTENTE = 'Produto Inexistente';

  NCM_BUSCAR_POR_NCM = '30029000';   //NCM ADJUVANTE
  NCM_BUSCAR_NCM_NAO_ENCONTRADO = '000000000';
  NCM_PRODUTO_INCORRETO = 'NCM do produto incorreto';

  PRODUTO_NAO_ENCONTRADO = 'Produto não encontrado. ';
  PRODUTO_NAO_ENCONTRADO_CODIGO = PRODUTO_NAO_ENCONTRADO + 'Codigo: ';
  PRODUTO_NAO_ENCONTRADO_DESCRICAO = PRODUTO_NAO_ENCONTRADO + 'Descricao: ';
  PRODUTO_NAO_ENCONTRADO_NCM = PRODUTO_NAO_ENCONTRADO + 'NCM: ';

implementation

end.
